#!/usr/bin/env python3
"""Create the reviewed demo stack with explicitly selected runtime integrations."""
import argparse
import json
import os
import re
from pathlib import Path
import secrets
import subprocess
import tempfile
from runtime_config import runtime_config

parser = argparse.ArgumentParser()
parser.add_argument('--profile', default='pennyahead')
parser.add_argument('--region', default='us-east-1', choices=['us-east-1'])
parser.add_argument('--vpc', required=True)
parser.add_argument('--subnet', required=True)
parser.add_argument('--commit', required=True)
parser.add_argument('--assistant', choices=['mock', 'bedrock'], default='mock')
parser.add_argument('--runtime-env-file', type=Path, help='Local env file; only Sandbox integration settings are selected')
parser.add_argument('--dry-run', action='store_true', help='Validate inputs and print a redacted plan without creating resources')
parser.add_argument('--domain', help='Full custom hostname, for example pennyahead.famtrees.net')
parser.add_argument('--certificate-arn', help='Issued us-east-1 ACM certificate covering --domain')
parser.add_argument('--invite-file', type=Path, required=True, help='Private JSON generated by deploy/create-invites.py')
args = parser.parse_args()
try:
    runtime = runtime_config(args.runtime_env_file, args.assistant)
except (OSError, ValueError) as error:
    parser.error(str(error))
try:
    invitations = json.loads(args.invite_file.read_text())['invitations']
    invite_hashes = [invite['hash'] for invite in invitations]
    if not 1 <= len(invite_hashes) <= 50 or not all(re.fullmatch(r'[a-f0-9]{64}', value) for value in invite_hashes):
        raise ValueError('Invalid invitation hashes')
except (OSError, ValueError, KeyError, TypeError):
    parser.error('Provide a private invitation file containing 1 to 50 valid SHA-256 hashes.')
if len(args.commit) != 40 or any(c not in '0123456789abcdef' for c in args.commit):
    raise SystemExit('Use the exact 40-character reviewed public Git commit.')
if bool(args.domain) != bool(args.certificate_arn):
    parser.error('Provide both --domain and --certificate-arn.')
if args.domain:
    if len(args.domain) > 253 or not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+', args.domain):
        parser.error('Use a lowercase DNS hostname without a protocol, port or path.')
    if not re.fullmatch(r'arn:aws:acm:us-east-1:\d{12}:certificate/[a-f0-9-]{36}', args.certificate_arn):
        parser.error('Use an ACM certificate ARN in us-east-1.')
    certificate = json.loads(subprocess.check_output([
        'aws', 'acm', 'describe-certificate', '--profile', args.profile,
        '--region', args.region, '--certificate-arn', args.certificate_arn,
        '--query', 'Certificate.{Status:Status,Names:SubjectAlternativeNames}', '--output', 'json',
    ], text=True))
    covered = any(name == args.domain or (name.startswith('*.') and args.domain.split('.', 1)[1] == name[2:])
        for name in certificate.get('Names', []))
    if certificate.get('Status') != 'ISSUED' or not covered:
        raise SystemExit('The certificate must be issued and cover the exact custom hostname before deployment.')
params = [{'ParameterKey': key, 'ParameterValue': value} for key, value in {
    'VpcId': args.vpc, 'SubnetId': args.subnet, 'Commit': args.commit,
    'OriginToken': secrets.token_hex(32),
    'InviteHashes': ','.join(invite_hashes), 'AccessSecret': secrets.token_hex(32),
    'DomainName': args.domain or '', 'CertificateArn': args.certificate_arn or '',
    'AssistantMode': args.assistant, 'RuntimeConfig': json.dumps(runtime),
}.items()]
if args.dry_run:
    print(json.dumps({'commit': args.commit, 'assistant': args.assistant,
        'runtimeKeys': sorted(runtime), 'domain': args.domain or 'CloudFront HTTPS hostname',
        'instanceType': 't3.small', 'volumeGiB': 24, 'invitations': len(invite_hashes)}))
    raise SystemExit(0)
with tempfile.NamedTemporaryFile(mode='w', prefix='pennyahead-parameters-', suffix='.json') as handle:
    os.chmod(handle.name, 0o600)
    json.dump(params, handle)
    handle.flush()
    subprocess.run(['aws', 'cloudformation', 'create-stack', '--profile', args.profile,
        '--region', args.region, '--stack-name', 'pennyahead-demo',
        '--template-body', f'file://{Path(__file__).resolve().with_name("aws.yml")}',
        '--parameters', f'file://{handle.name}', '--capabilities', 'CAPABILITY_IAM',
        '--tags', 'Key=Project,Value=PennyAhead'], check=True)
